### ISSUE TITLE
affected_rows is undefined

### ISSUE THREAD

**Issue by soulcurrymedia** [yhirano55/activerecord-explainer#5]
Could not log "sql.active_record" event. NameError: undefined local variable or method `affected_rows' for #<ActiveRecord::Explainer::
Subscriber:0x000055e7a9506cc0>                                                                                                        
Did you mean?  affectet_rows

A small one :)

**Comment by shingara** [comment]
currently not works with rails 6.1 :(
